os: linux

language: go

env:
  - GO111MODULE=on

go:
  - 1.14.x

install:
  - true

notifications:
  email: false

cache:
  directories:
    - $GOPATH/pkg/mod
    - /home/travis/.cache/go-build

script:
  - go test -v -race
  - go test -bench=.